# Numpy

In [1]:
import numpy as np 
a = np.array([[[2,3,4]],[[2,5,6]]])

In [2]:
a

array([[[2, 3, 4]],

       [[2, 5, 6]]])

In [3]:
np.ones((2,3,4),dtype = bool) #(layers,Rows,columns)

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [4]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
np.arange(6).reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Ravel and flatten

In [7]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
a[0][1] = 202
a

array([[  0, 202,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [9]:
v = a.ravel()

In [10]:
w = a.flatten()

In [11]:
v

array([  0, 202,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [12]:
w

array([  0, 202,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

# Transpose

In [13]:
a.T

array([[  0,   5,  10,  15,  20],
       [202,   6,  11,  16,  21],
       [  2,   7,  12,  17,  22],
       [  3,   8,  13,  18,  23],
       [  4,   9,  14,  19,  24]])

In [14]:
a

array([[  0, 202,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

# Numpy Operations

In [15]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
y = np.arange(11,20).reshape(3,3)
y

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [17]:
np.add(x,y)

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [18]:
np.subtract(x,y)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [19]:
np.multiply(x,y)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [20]:
np.divide(x,y)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [21]:
x.dot(y)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [22]:
a = np.sin(x)

In [23]:
np.sin(y)

array([[-0.99999021, -0.53657292,  0.42016704],
       [ 0.99060736,  0.65028784, -0.28790332],
       [-0.96139749, -0.75098725,  0.14987721]])

In [24]:
b = np.cos(x)

In [25]:
print(a/b)

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [26]:
print(1/a)

[[ 1.18839511  1.09975017  7.0861674 ]
 [-1.32134871 -1.04283521 -3.57889955]
 [ 1.52210106  1.01075622  2.42648664]]


In [27]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a.min(axis=0)

array([1, 2, 3])

In [29]:
a.argmin()

0

In [30]:
a.argmax()

8

In [31]:
a.max(axis=0)

array([7, 8, 9])

In [32]:
np.sum(a,axis=0)

array([12, 15, 18])

## Slicing

In [33]:
import numpy as np 

In [34]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
a[0]

array([1, 2, 3, 4, 5])

In [36]:
a[0,0]

1

In [37]:
a[2,1:4]

array([12, 13, 14])

In [38]:
a[2:3,1:4]

array([[12, 13, 14]])

In [39]:
a[4:5,1:5]

array([[22, 23, 24, 25]])

In [40]:
a[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [41]:
a[0:4:3,0:3:1]

array([[ 1,  2,  3],
       [16, 17, 18]])

In [42]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
b = np.arange(11,20).reshape(3,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [44]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [45]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [46]:
np.concatenate((a,b)).T

array([[ 1,  4,  7, 11, 14, 17],
       [ 2,  5,  8, 12, 15, 18],
       [ 3,  6,  9, 13, 16, 19]])

In [47]:
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [48]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# Split

In [49]:
c = np.arange(1,25).reshape(6,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [50]:
np.split(c,3,axis = 0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [51]:
np.random.random((3,2))

array([[0.90576291, 0.01613975],
       [0.30517036, 0.66222843],
       [0.47622603, 0.91147532]])

In [52]:
np.random.random((2,3,2))

array([[[0.49485943, 0.66774585],
        [0.4176156 , 0.43927288],
        [0.49817961, 0.60086489]],

       [[0.95988939, 0.85172929],
        [0.88370401, 0.29276897],
        [0.41843417, 0.34516045]]])

In [53]:
np.random.randint((1,5,4))

array([0, 4, 0])

In [54]:
np.random.randint(1,5,(2,4))

array([[2, 2, 4, 4],
       [1, 3, 2, 2]])

In [55]:
np.random.randint(1,10,(2,4,4))

array([[[9, 4, 9, 2],
        [9, 4, 8, 9],
        [8, 3, 2, 3],
        [8, 3, 5, 8]],

       [[7, 1, 2, 5],
        [7, 3, 4, 7],
        [6, 9, 5, 2],
        [4, 8, 4, 2]]])

In [56]:
np.random.seed(0) #keeps values same
np.random.randint(1,10,(2,4,4))

array([[[6, 1, 4, 4],
        [8, 4, 6, 3],
        [5, 8, 7, 9],
        [9, 2, 7, 8]],

       [[8, 9, 2, 6],
        [9, 5, 4, 1],
        [4, 6, 1, 3],
        [4, 9, 2, 4]]])

In [57]:
str1 = "I m not a body"
str2 = "I m consciousness"
np.char.add(str1,str2)

array('I m not a bodyI m consciousness', dtype='<U31')

In [58]:
np.char.multiply(str1,2)

array('I m not a bodyI m not a body', dtype='<U28')

In [59]:
np.char.lower(str1)

array('i m not a body', dtype='<U14')

In [60]:
np.char.upper(str1)

array('I M NOT A BODY', dtype='<U14')

In [61]:
np.char.center(str1,30)

array('        I m not a body        ', dtype='<U30')

In [62]:
np.char.center(str1,30,fillchar="*")

array('********I m not a body********', dtype='<U30')

In [63]:
np.char.split(str1)

array(list(['I', 'm', 'not', 'a', 'body']), dtype=object)

In [64]:
np.char.splitlines("hello\nworld")

array(list(['hello', 'world']), dtype=object)

In [65]:
s1 = 'high'
s2 = 'low'
np.char.join(['%','*'],[s1,s2])

array(['h%i%g%h', 'l*o*w'], dtype='<U7')

In [66]:
np.char.replace(str1,'m','M')

array('I M not a body', dtype='<U14')

In [67]:
np.char.equal(str1,str2)

array(False)

In [68]:
np.char.count(str1,"a")

array(1)

In [69]:
np.char.find(str1,"a")

array(8)

In [70]:
a = np.arange(1,4)

In [71]:
b = np.array([6])

In [72]:
np.add(a,b)

array([7, 8, 9])

In [73]:
d = np.arange(1,10).reshape(3,3)

In [74]:
np.add(b,d)

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Pandas

In [75]:
import pandas as pd

## Series

In [76]:
list = [1,2,3,4,5]
pd.Series(list)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [77]:
pd.Series(list, index = ['A','B','C','D','E'])

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [78]:
pd.Series(list, index = ['A','B','C','D','E'],dtype = float,name = 'data_values')

A    1.0
B    2.0
C    3.0
D    4.0
E    5.0
Name: data_values, dtype: float64

In [79]:
pd.Series({'a':1,'b':2})

a    1
b    2
dtype: int64

In [80]:
a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [81]:
a[2]

3

In [82]:
a[1:4]

1    2
2    3
3    4
dtype: int64

In [83]:
a[a>2]

2    3
3    4
4    5
dtype: int64

In [84]:
b = pd.Series([11,12,13,14,15])
b

0    11
1    12
2    13
3    14
4    15
dtype: int64

In [85]:
np.add(a,b)

0    12
1    14
2    16
3    18
4    20
dtype: int64

In [86]:
np.divide(a,b)

0    0.090909
1    0.166667
2    0.230769
3    0.285714
4    0.333333
dtype: float64

In [87]:
np.subtract(a,b)

0   -10
1   -10
2   -10
3   -10
4   -10
dtype: int64

In [88]:
np.multiply(a,b)

0    11
1    24
2    39
3    56
4    75
dtype: int64

In [89]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [90]:
pd.DataFrame(a)

0
0  1
1  2
2  3
3  4
4  5

In [91]:
c = np.arange(1,10).reshape(3,3)

In [92]:
pd.DataFrame(c)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [93]:
pd.DataFrame({'id':[1,2,3],'id_1':[4,5,6]})

id  id_1
0   1     4
1   2     5
2   3     6

# Pandas

In [94]:
import pandas as pd
data = 'C:\\Users\\Admin\\Downloads\\Movieratingdata.csv'
df = pd.read_csv('C:\\Users\\Admin\\Downloads\\Movieratingdata.csv')


In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   USER_ID          500 non-null    int64  
 1   MOVIE_ID         500 non-null    int64  
 2   MOVIE_TITLE      500 non-null    object 
 3   PRODUCTION_YEAR  500 non-null    int64  
 4   GENRES           500 non-null    object 
 5   RATING           500 non-null    float64
 6   Unnamed: 6       0 non-null      float64
 7   Unnamed: 7       2 non-null      float64
 8   GENRES.1         5 non-null      object 
 9   Unnamed: 9       4 non-null      float64
dtypes: float64(4), int64(3), object(3)
memory usage: 39.2+ KB


In [96]:
df.columns

Index(['USER_ID', 'MOVIE_ID', 'MOVIE_TITLE', 'PRODUCTION_YEAR', 'GENRES',
       'RATING', 'Unnamed: 6', 'Unnamed: 7', 'GENRES.1', 'Unnamed: 9'],
      dtype='object')

In [97]:
type(df)

pandas.core.frame.DataFrame

In [98]:
df.head(4)

USER_ID  MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044                     Riot              2015   
1        2   1925518          The Protector 2              2013   
2        3    372784            Batman Begins              2005   
3        4   1390411  In the Heart of the Sea              2015   

                                              GENRES  RATING  Unnamed: 6  \
0                                             Action     8.0         NaN   
1                                             Action     5.0         NaN   
2                                   Action|Adventure     9.0         NaN   
3  Action|Adventure|Biography|Drama|History|Thriller     5.0         NaN   

   Unnamed: 7  GENRES.1  Unnamed: 9  
0         1.0    action         8.0  
1         5.0  suspense         6.0  
2         NaN     drama         5.0  
3         NaN  thriller         4.0

In [99]:
pd.read_csv(data,nrows = 4)

USER_ID  MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044                     Riot              2015   
1        2   1925518          The Protector 2              2013   
2        3    372784            Batman Begins              2005   
3        4   1390411  In the Heart of the Sea              2015   

                                              GENRES  RATING  Unnamed: 6  \
0                                             Action       8         NaN   
1                                             Action       5         NaN   
2                                   Action|Adventure       9         NaN   
3  Action|Adventure|Biography|Drama|History|Thriller       5         NaN   

   Unnamed: 7  GENRES.1  Unnamed: 9  
0         1.0    action           8  
1         5.0  suspense           6  
2         NaN     drama           5  
3         NaN  thriller           4

In [100]:
pd.read_csv(data,skiprows = 10)

10  1663202        The Revenant   2015  \
0     11  1663202        The Revenant   2015   
1     12  1663202        The Revenant   2015   
2     13  1663202        The Revenant   2015   
3     14  1663202        The Revenant   2015   
4     15  1663202        The Revenant   2015   
..   ...      ...                  ...   ...   
485  496  1846589       Hunter Killer   2018   
486  497  4196776        Jason Bourne   2016   
487  498  7456310                Anna   2019   
488  499  8106534       6 Underground   2019   
489  500  2302755  Olympus Has Fallen   2013   

     Action|Adventure|Biography|Drama|Western    9  Unnamed: 6  Unnamed: 7  \
0    Action|Adventure|Biography|Drama|Western  9.2         NaN         NaN   
1    Action|Adventure|Biography|Drama|Western  6.0         NaN         NaN   
2    Action|Adventure|Biography|Drama|Western  9.0         NaN         NaN   
3    Action|Adventure|Biography|Drama|Western  8.0         NaN         NaN   
4    Action|Adventure|Biography|Drama|Western  7.0         NaN         NaN   
..                                        ...  ...         ...         ...   
485                           Action|Thriller  6.0         NaN         NaN   
486                           Action|Thriller  6.0         NaN         NaN   
487                           Action|Thriller  7.0         NaN         NaN   
488                           Action|Thriller  4.0         NaN         NaN   
489                           Action|Thriller  1.0         NaN         NaN   

     Unnamed: 8  Unnamed: 9  
0           NaN         NaN  
1           NaN         NaN  
2           NaN         NaN  
3           NaN         NaN  
4           NaN         NaN  
..          ...         ...  
485         NaN         NaN  
486         NaN         NaN  
487         NaN         NaN  
488         NaN         NaN  
489         NaN         NaN  

[490 rows x 10 columns]

In [101]:
pd.read_csv(data,skiprows = [2,4,6])

USER_ID  MOVIE_ID          MOVIE_TITLE  PRODUCTION_YEAR  \
0          1   4642044                Riot              2015   
1          3    372784       Batman Begins              2005   
2          5   6306064              Adrift              2018   
3          7   2719848             Everest              2015   
4          8    462504         Rescue Dawn              2006   
..       ...       ...                  ...              ...   
492      496   1846589       Hunter Killer              2018   
493      497   4196776        Jason Bourne              2016   
494      498   7456310                Anna              2019   
495      499   8106534       6 Underground              2019   
496      500   2302755  Olympus Has Fallen              2013   

                                                GENRES  RATING  Unnamed: 6  \
0                                               Action     8.0         NaN   
1                                     Action|Adventure     9.0         NaN   
2    Action|Adventure|Biography|Drama|Romance|Thriller     4.0         NaN   
3            Action|Adventure|Biography|Drama|Thriller     6.0         NaN   
4                 Action|Adventure|Biography|Drama|War     8.0         NaN   
..                                                 ...     ...         ...   
492                                    Action|Thriller     6.0         NaN   
493                                    Action|Thriller     6.0         NaN   
494                                    Action|Thriller     7.0         NaN   
495                                    Action|Thriller     4.0         NaN   
496                                    Action|Thriller     1.0         NaN   

     Unnamed: 7    GENRES.1  Unnamed: 9  
0           1.0      action         8.0  
1           NaN       drama         5.0  
2           NaN  adventures         NaN  
3           NaN         NaN         NaN  
4           NaN         NaN         NaN  
..          ...         ...         ...  
492         NaN         NaN         NaN  
493         NaN         NaN         NaN  
494         NaN         NaN         NaN  
495         NaN         NaN         NaN  
496         NaN         NaN         NaN  

[497 rows x 10 columns]

In [102]:
pd.read_csv(data,index_col = 'USER_ID')

MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR  \
USER_ID                                                        
1         4642044                     Riot              2015   
2         1925518          The Protector 2              2013   
3          372784            Batman Begins              2005   
4         1390411  In the Heart of the Sea              2015   
5         6306064                   Adrift              2018   
...           ...                       ...              ...   
496       1846589            Hunter Killer              2018   
497       4196776             Jason Bourne              2016   
498       7456310                     Anna              2019   
499       8106534            6 Underground              2019   
500       2302755       Olympus Has Fallen              2013   

                                                    GENRES  RATING  \
USER_ID                                                              
1                                                   Action     8.0   
2                                                   Action     5.0   
3                                         Action|Adventure     9.0   
4        Action|Adventure|Biography|Drama|History|Thriller     5.0   
5        Action|Adventure|Biography|Drama|Romance|Thriller     4.0   
...                                                    ...     ...   
496                                        Action|Thriller     6.0   
497                                        Action|Thriller     6.0   
498                                        Action|Thriller     7.0   
499                                        Action|Thriller     4.0   
500                                        Action|Thriller     1.0   

         Unnamed: 6  Unnamed: 7    GENRES.1  Unnamed: 9  
USER_ID                                                  
1               NaN         1.0      action         8.0  
2               NaN         5.0    suspense         6.0  
3               NaN         NaN       drama         5.0  
4               NaN         NaN    thriller         4.0  
5               NaN         NaN  adventures         NaN  
...             ...         ...         ...         ...  
496             NaN         NaN         NaN         NaN  
497             NaN         NaN         NaN         NaN  
498             NaN         NaN         NaN         NaN  
499             NaN         NaN         NaN         NaN  
500             NaN         NaN         NaN         NaN  

[500 rows x 9 columns]

In [103]:
pd.read_csv(data,index_col = ['USER_ID','PRODUCTION_YEAR'])

MOVIE_ID               MOVIE_TITLE  \
USER_ID PRODUCTION_YEAR                                       
1       2015              4642044                     Riot    
2       2013              1925518          The Protector 2    
3       2005               372784            Batman Begins    
4       2015              1390411  In the Heart of the Sea    
5       2018              6306064                   Adrift    
...                           ...                       ...   
496     2018              1846589            Hunter Killer    
497     2016              4196776             Jason Bourne    
498     2019              7456310                     Anna    
499     2019              8106534            6 Underground    
500     2013              2302755       Olympus Has Fallen    

                                                                    GENRES  \
USER_ID PRODUCTION_YEAR                                                      
1       2015                                                        Action   
2       2013                                                        Action   
3       2005                                              Action|Adventure   
4       2015             Action|Adventure|Biography|Drama|History|Thriller   
5       2018             Action|Adventure|Biography|Drama|Romance|Thriller   
...                                                                    ...   
496     2018                                               Action|Thriller   
497     2016                                               Action|Thriller   
498     2019                                               Action|Thriller   
499     2019                                               Action|Thriller   
500     2013                                               Action|Thriller   

                         RATING  Unnamed: 6  Unnamed: 7    GENRES.1  \
USER_ID PRODUCTION_YEAR                                               
1       2015                8.0         NaN         1.0      action   
2       2013                5.0         NaN         5.0    suspense   
3       2005                9.0         NaN         NaN       drama   
4       2015                5.0         NaN         NaN    thriller   
5       2018                4.0         NaN         NaN  adventures   
...                         ...         ...         ...         ...   
496     2018                6.0         NaN         NaN         NaN   
497     2016                6.0         NaN         NaN         NaN   
498     2019                7.0         NaN         NaN         NaN   
499     2019                4.0         NaN         NaN         NaN   
500     2013                1.0         NaN         NaN         NaN   

                         Unnamed: 9  
USER_ID PRODUCTION_YEAR              
1       2015                    8.0  
2       2013                    6.0  
3       2005                    5.0  
4       2015                    4.0  
5       2018                    NaN  
...                             ...  
496     2018                    NaN  
497     2016                    NaN  
498     2019                    NaN  
499     2019                    NaN  
500     2013                    NaN  

[500 rows x 8 columns]

In [104]:
pd.read_csv(data,index_col =[0,1])

MOVIE_TITLE  PRODUCTION_YEAR  \
USER_ID MOVIE_ID                                              
1       4642044                      Riot              2015   
2       1925518           The Protector 2              2013   
3       372784              Batman Begins              2005   
4       1390411   In the Heart of the Sea              2015   
5       6306064                    Adrift              2018   
...                                    ...              ...   
496     1846589             Hunter Killer              2018   
497     4196776              Jason Bourne              2016   
498     7456310                      Anna              2019   
499     8106534             6 Underground              2019   
500     2302755        Olympus Has Fallen              2013   

                                                             GENRES  RATING  \
USER_ID MOVIE_ID                                                              
1       4642044                                              Action     8.0   
2       1925518                                              Action     5.0   
3       372784                                     Action|Adventure     9.0   
4       1390411   Action|Adventure|Biography|Drama|History|Thriller     5.0   
5       6306064   Action|Adventure|Biography|Drama|Romance|Thriller     4.0   
...                                                             ...     ...   
496     1846589                                     Action|Thriller     6.0   
497     4196776                                     Action|Thriller     6.0   
498     7456310                                     Action|Thriller     7.0   
499     8106534                                     Action|Thriller     4.0   
500     2302755                                     Action|Thriller     1.0   

                  Unnamed: 6  Unnamed: 7    GENRES.1  Unnamed: 9  
USER_ID MOVIE_ID                                                  
1       4642044          NaN         1.0      action         8.0  
2       1925518          NaN         5.0    suspense         6.0  
3       372784           NaN         NaN       drama         5.0  
4       1390411          NaN         NaN    thriller         4.0  
5       6306064          NaN         NaN  adventures         NaN  
...                      ...         ...         ...         ...  
496     1846589          NaN         NaN         NaN         NaN  
497     4196776          NaN         NaN         NaN         NaN  
498     7456310          NaN         NaN         NaN         NaN  
499     8106534          NaN         NaN         NaN         NaN  
500     2302755          NaN         NaN         NaN         NaN  

[500 rows x 8 columns]

In [105]:
pd.read_csv(data,header=None)

0         1                         2                3  \
0    USER_ID  MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR   
1          1   4642044                     Riot              2015   
2          2   1925518          The Protector 2              2013   
3          3    372784            Batman Begins              2005   
4          4   1390411  In the Heart of the Sea              2015   
..       ...       ...                       ...              ...   
496      496   1846589            Hunter Killer              2018   
497      497   4196776             Jason Bourne              2016   
498      498   7456310                     Anna              2019   
499      499   8106534            6 Underground              2019   
500      500   2302755       Olympus Has Fallen              2013   

                                                     4       5   6    7  \
0                                               GENRES  RATING NaN  NaN   
1                                               Action       8 NaN  1.0   
2                                               Action       5 NaN  5.0   
3                                     Action|Adventure       9 NaN  NaN   
4    Action|Adventure|Biography|Drama|History|Thriller       5 NaN  NaN   
..                                                 ...     ...  ..  ...   
496                                    Action|Thriller       6 NaN  NaN   
497                                    Action|Thriller       6 NaN  NaN   
498                                    Action|Thriller       7 NaN  NaN   
499                                    Action|Thriller       4 NaN  NaN   
500                                    Action|Thriller       1 NaN  NaN   

            8    9  
0      GENRES  NaN  
1      action  8.0  
2    suspense  6.0  
3       drama  5.0  
4    thriller  4.0  
..        ...  ...  
496       NaN  NaN  
497       NaN  NaN  
498       NaN  NaN  
499       NaN  NaN  
500       NaN  NaN  

[501 rows x 10 columns]

In [106]:
pd.read_csv(data,header = None,prefix = 'col')

col0      col1                      col2             col3  \
0    USER_ID  MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR   
1          1   4642044                     Riot              2015   
2          2   1925518          The Protector 2              2013   
3          3    372784            Batman Begins              2005   
4          4   1390411  In the Heart of the Sea              2015   
..       ...       ...                       ...              ...   
496      496   1846589            Hunter Killer              2018   
497      497   4196776             Jason Bourne              2016   
498      498   7456310                     Anna              2019   
499      499   8106534            6 Underground              2019   
500      500   2302755       Olympus Has Fallen              2013   

                                                  col4    col5  col6  col7  \
0                                               GENRES  RATING   NaN   NaN   
1                                               Action       8   NaN   1.0   
2                                               Action       5   NaN   5.0   
3                                     Action|Adventure       9   NaN   NaN   
4    Action|Adventure|Biography|Drama|History|Thriller       5   NaN   NaN   
..                                                 ...     ...   ...   ...   
496                                    Action|Thriller       6   NaN   NaN   
497                                    Action|Thriller       6   NaN   NaN   
498                                    Action|Thriller       7   NaN   NaN   
499                                    Action|Thriller       4   NaN   NaN   
500                                    Action|Thriller       1   NaN   NaN   

         col8  col9  
0      GENRES   NaN  
1      action   8.0  
2    suspense   6.0  
3       drama   5.0  
4    thriller   4.0  
..        ...   ...  
496       NaN   NaN  
497       NaN   NaN  
498       NaN   NaN  
499       NaN   NaN  
500       NaN   NaN  

[501 rows x 10 columns]

In [107]:
pd.read_csv(data,names = [1,2,3,4,5,6,7,8,9,0]) #change names of columns

1         2                         3                4  \
0    USER_ID  MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR   
1          1   4642044                     Riot              2015   
2          2   1925518          The Protector 2              2013   
3          3    372784            Batman Begins              2005   
4          4   1390411  In the Heart of the Sea              2015   
..       ...       ...                       ...              ...   
496      496   1846589            Hunter Killer              2018   
497      497   4196776             Jason Bourne              2016   
498      498   7456310                     Anna              2019   
499      499   8106534            6 Underground              2019   
500      500   2302755       Olympus Has Fallen              2013   

                                                     5       6   7    8  \
0                                               GENRES  RATING NaN  NaN   
1                                               Action       8 NaN  1.0   
2                                               Action       5 NaN  5.0   
3                                     Action|Adventure       9 NaN  NaN   
4    Action|Adventure|Biography|Drama|History|Thriller       5 NaN  NaN   
..                                                 ...     ...  ..  ...   
496                                    Action|Thriller       6 NaN  NaN   
497                                    Action|Thriller       6 NaN  NaN   
498                                    Action|Thriller       7 NaN  NaN   
499                                    Action|Thriller       4 NaN  NaN   
500                                    Action|Thriller       1 NaN  NaN   

            9    0  
0      GENRES  NaN  
1      action  8.0  
2    suspense  6.0  
3       drama  5.0  
4    thriller  4.0  
..        ...  ...  
496       NaN  NaN  
497       NaN  NaN  
498       NaN  NaN  
499       NaN  NaN  
500       NaN  NaN  

[501 rows x 10 columns]

In [108]:
df.head()

USER_ID  MOVIE_ID               MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044                     Riot              2015   
1        2   1925518          The Protector 2              2013   
2        3    372784            Batman Begins              2005   
3        4   1390411  In the Heart of the Sea              2015   
4        5   6306064                   Adrift              2018   

                                              GENRES  RATING  Unnamed: 6  \
0                                             Action     8.0         NaN   
1                                             Action     5.0         NaN   
2                                   Action|Adventure     9.0         NaN   
3  Action|Adventure|Biography|Drama|History|Thriller     5.0         NaN   
4  Action|Adventure|Biography|Drama|Romance|Thriller     4.0         NaN   

   Unnamed: 7    GENRES.1  Unnamed: 9  
0         1.0      action         8.0  
1         5.0    suspense         6.0  
2         NaN       drama         5.0  
3         NaN    thriller         4.0  
4         NaN  adventures         NaN

## Handling missing values

In [109]:
data = 'Downloads//Movieratingdata1.csv'
df = pd.read_csv('Downloads//Movieratingdata1.csv')

In [110]:
pd.read_csv(data,na_values = ['not available'])

USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0    4642044          Riot             2015   
1       NaN        NaN            NaN             NaN   
2       3.0  not value            NaN            2014   
3       4.0    1390411            NaN            2015   
4       5.0    6306064            NaN             NaN   
5       6.0    6306064            NaN     not mension   
6       7.0    2719848            NaN            2015   
7       8.0     462504            NaN            2006   
8       9.0        NaN            NaN            2020   
9      10.0     163225  The Revenant             2015   
10     11.0    1663202            NaN            2015   
11     12.0    1663202  The Revenant             2021   

                                               GENRES       RATING  
0                                              Action          NaN  
1                                                 NaN          NaN  
2                                                 NaN          NaN  
3                                                 NaN            5  
4   Action|Adventure|Biography|Drama|Romance|Thriller            4  
5   Action|Adventure|Biography|Drama|Romance|Thriller            5  
6           Action|Adventure|Biography|Drama|Thriller          NaN  
7                Action|Adventure|Biography|Drama|War  not mension  
8            Action|Adventure|Biography|Drama|Western           10  
9            Action|Adventure|Biography|Drama|Western            9  
10           Action|Adventure|Biography|Drama|Western            9  
11           Action|Adventure|Biography|Drama|Western            6

In [111]:
pd.read_csv(data,na_values = {'PRODUCTION_YEAR' : 'not available'}) # replacing specific values in particular column

USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0    4642044          Riot             2015   
1       NaN        NaN            NaN             NaN   
2       3.0  not value            NaN            2014   
3       4.0    1390411            NaN            2015   
4       5.0    6306064            NaN             NaN   
5       6.0    6306064            NaN     not mension   
6       7.0    2719848            NaN            2015   
7       8.0     462504            NaN            2006   
8       9.0        NaN            NaN            2020   
9      10.0     163225  The Revenant             2015   
10     11.0    1663202            NaN            2015   
11     12.0    1663202  The Revenant             2021   

                                               GENRES         RATING  
0                                              Action            NaN  
1                                                 NaN            NaN  
2                                                 NaN            NaN  
3                                                 NaN              5  
4   Action|Adventure|Biography|Drama|Romance|Thriller              4  
5   Action|Adventure|Biography|Drama|Romance|Thriller              5  
6           Action|Adventure|Biography|Drama|Thriller  not available  
7                Action|Adventure|Biography|Drama|War    not mension  
8            Action|Adventure|Biography|Drama|Western             10  
9            Action|Adventure|Biography|Drama|Western              9  
10           Action|Adventure|Biography|Drama|Western              9  
11           Action|Adventure|Biography|Drama|Western              6

In [112]:
pd.read_csv(data,keep_default_na=False)

USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0        1    4642044          Riot             2015   
1                #N/A                                  
2        3  not value                           2014   
3        4    1390411                           2015   
4        5    6306064                  not available   
5        6    6306064                    not mension   
6        7    2719848                           2015   
7        8     462504                           2006   
8        9       NULL                           2020   
9       10     163225  The Revenant             2015   
10      11    1663202                           2015   
11      12    1663202  The Revenant             2021   

                                               GENRES         RATING  
0                                              Action                 
1                                                                     
2                                                                     
3                                                                  5  
4   Action|Adventure|Biography|Drama|Romance|Thriller              4  
5   Action|Adventure|Biography|Drama|Romance|Thriller              5  
6           Action|Adventure|Biography|Drama|Thriller  not available  
7                Action|Adventure|Biography|Drama|War    not mension  
8            Action|Adventure|Biography|Drama|Western             10  
9            Action|Adventure|Biography|Drama|Western              9  
10           Action|Adventure|Biography|Drama|Western              9  
11           Action|Adventure|Biography|Drama|Western              6

In [113]:
df.isnull().sum().sum() # total NaN values

19

In [114]:
df.notnull().sum().sum() # total not NaN values

53

In [115]:
df.dropna()

USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
9      10.0   163225  The Revenant             2015   
11     12.0  1663202  The Revenant             2021   

                                      GENRES RATING  
9   Action|Adventure|Biography|Drama|Western      9  
11  Action|Adventure|Biography|Drama|Western      6

In [116]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [117]:
df.dropna(how='all')

USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0    4642044          Riot             2015   
2       3.0  not value            NaN            2014   
3       4.0    1390411            NaN            2015   
4       5.0    6306064            NaN   not available   
5       6.0    6306064            NaN     not mension   
6       7.0    2719848            NaN            2015   
7       8.0     462504            NaN            2006   
8       9.0        NaN            NaN            2020   
9      10.0     163225  The Revenant             2015   
10     11.0    1663202            NaN            2015   
11     12.0    1663202  The Revenant             2021   

                                               GENRES         RATING  
0                                              Action            NaN  
2                                                 NaN            NaN  
3                                                 NaN              5  
4   Action|Adventure|Biography|Drama|Romance|Thriller              4  
5   Action|Adventure|Biography|Drama|Romance|Thriller              5  
6           Action|Adventure|Biography|Drama|Thriller  not available  
7                Action|Adventure|Biography|Drama|War    not mension  
8            Action|Adventure|Biography|Drama|Western             10  
9            Action|Adventure|Biography|Drama|Western              9  
10           Action|Adventure|Biography|Drama|Western              9  
11           Action|Adventure|Biography|Drama|Western              6

In [118]:
df.dropna(thresh=2) #minmum 2 values required otherwise it will drop that rows

USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0    4642044          Riot             2015   
2       3.0  not value            NaN            2014   
3       4.0    1390411            NaN            2015   
4       5.0    6306064            NaN   not available   
5       6.0    6306064            NaN     not mension   
6       7.0    2719848            NaN            2015   
7       8.0     462504            NaN            2006   
8       9.0        NaN            NaN            2020   
9      10.0     163225  The Revenant             2015   
10     11.0    1663202            NaN            2015   
11     12.0    1663202  The Revenant             2021   

                                               GENRES         RATING  
0                                              Action            NaN  
2                                                 NaN            NaN  
3                                                 NaN              5  
4   Action|Adventure|Biography|Drama|Romance|Thriller              4  
5   Action|Adventure|Biography|Drama|Romance|Thriller              5  
6           Action|Adventure|Biography|Drama|Thriller  not available  
7                Action|Adventure|Biography|Drama|War    not mension  
8            Action|Adventure|Biography|Drama|Western             10  
9            Action|Adventure|Biography|Drama|Western              9  
10           Action|Adventure|Biography|Drama|Western              9  
11           Action|Adventure|Biography|Drama|Western              6

In [119]:
df.dropna(subset=['PRODUCTION_YEAR'])

USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0    4642044          Riot             2015   
2       3.0  not value            NaN            2014   
3       4.0    1390411            NaN            2015   
4       5.0    6306064            NaN   not available   
5       6.0    6306064            NaN     not mension   
6       7.0    2719848            NaN            2015   
7       8.0     462504            NaN            2006   
8       9.0        NaN            NaN            2020   
9      10.0     163225  The Revenant             2015   
10     11.0    1663202            NaN            2015   
11     12.0    1663202  The Revenant             2021   

                                               GENRES         RATING  
0                                              Action            NaN  
2                                                 NaN            NaN  
3                                                 NaN              5  
4   Action|Adventure|Biography|Drama|Romance|Thriller              4  
5   Action|Adventure|Biography|Drama|Romance|Thriller              5  
6           Action|Adventure|Biography|Drama|Thriller  not available  
7                Action|Adventure|Biography|Drama|War    not mension  
8            Action|Adventure|Biography|Drama|Western             10  
9            Action|Adventure|Biography|Drama|Western              9  
10           Action|Adventure|Biography|Drama|Western              9  
11           Action|Adventure|Biography|Drama|Western              6

In [120]:
data = 'Downloads/Movieratingdata3.csv'
df = pd.read_csv('Downloads/Movieratingdata3.csv')
df

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2015.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897     Ironman              NaN   
3        4   1390411     Ironman              NaN   
4        5   6306064     Ironman           2019.0   
5        6   6306064     Ironman           2020.0   
6        7   2719848     Ironman           2015.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [121]:
df.replace(to_replace = 'Ironman', value = 'AVENGERS')

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2015.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897    AVENGERS              NaN   
3        4   1390411    AVENGERS              NaN   
4        5   6306064    AVENGERS           2019.0   
5        6   6306064    AVENGERS           2020.0   
6        7   2719848    AVENGERS           2015.0   
7        8    462504    AVENGERS           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [122]:
df.replace(to_replace = ['Ironman','tiger'], value = ['batman','lion'])

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2015.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897      batman              NaN   
3        4   1390411      batman              NaN   
4        5   6306064      batman           2019.0   
5        6   6306064      batman           2020.0   
6        7   2719848      batman           2015.0   
7        8    462504      batman           2006.0   
8        9     25468        lion           2015.0   
9       10   2564789        lion           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [123]:
df.replace(to_replace = [1,2,3,4,5,6],value = 11)

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0       11   4642044       Riot            2015.0   
1       11   2536598       Ravan           2016.0   
2       11   1245897     Ironman              NaN   
3       11   1390411     Ironman              NaN   
4       11   6306064     Ironman           2019.0   
5       11   6306064     Ironman           2020.0   
6        7   2719848     Ironman           2015.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller      11  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western      11  
4  Action|Adventure|Biography|Drama|Romance|Thriller      11  
5  Action|Adventure|Biography|Drama|Romance|Thriller      11  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [124]:
df.replace({'PRODUCTION_YEAR':2015.0},2222)

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2222.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897     Ironman              NaN   
3        4   1390411     Ironman              NaN   
4        5   6306064     Ironman           2019.0   
5        6   6306064     Ironman           2020.0   
6        7   2719848     Ironman           2222.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2222.0   
9       10   2564789       tiger           2222.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [125]:
df.replace({'MOVIE_TITLE':'[A-Z]'},450,regex = True)

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044         450           2015.0   
1        2   2536598         450           2016.0   
2        3   1245897         450              NaN   
3        4   1390411         450              NaN   
4        5   6306064         450           2019.0   
5        6   6306064         450           2020.0   
6        7   2719848         450           2015.0   
7        8    462504         450           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [126]:
df.replace('[a-z]',400,regex = True)

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR GENRES  RATING
0        1   4642044         400           2015.0    400       8
1        2   2536598         400           2016.0    400       6
2        3   1245897         400              NaN    400       8
3        4   1390411         400              NaN    400       5
4        5   6306064         400           2019.0    400       4
5        6   6306064         400           2020.0    400       5
6        7   2719848         400           2015.0    400       9
7        8    462504         400           2006.0    400       9
8        9     25468         400           2015.0    400      10
9       10   2564789         400           2015.0    400       9

In [127]:
df.replace('IRONMAN',method = 'bfill')

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2015.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897     Ironman              NaN   
3        4   1390411     Ironman              NaN   
4        5   6306064     Ironman           2019.0   
5        6   6306064     Ironman           2020.0   
6        7   2719848     Ironman           2015.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [128]:
df.replace(2015,method = 'bfill')

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2016.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897     Ironman              NaN   
3        4   1390411     Ironman              NaN   
4        5   6306064     Ironman           2019.0   
5        6   6306064     Ironman           2020.0   
6        7   2719848     Ironman           2006.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [129]:
df.replace('Ironman',method = 'ffill',limit = 4)

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2015.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897       Ravan              NaN   
3        4   1390411       Ravan              NaN   
4        5   6306064       Ravan           2019.0   
5        6   6306064       Ravan           2020.0   
6        7   2719848     Ironman           2015.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

In [130]:
df

USER_ID  MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  \
0        1   4642044       Riot            2015.0   
1        2   2536598       Ravan           2016.0   
2        3   1245897     Ironman              NaN   
3        4   1390411     Ironman              NaN   
4        5   6306064     Ironman           2019.0   
5        6   6306064     Ironman           2020.0   
6        7   2719848     Ironman           2015.0   
7        8    462504     Ironman           2006.0   
8        9     25468       tiger           2015.0   
9       10   2564789       tiger           2015.0   

                                              GENRES  RATING  
0                                             Action       8  
1          Action|Adventure|Biography|Drama|Thriller       6  
2               Action|Adventure|Biography|Drama|War       8  
3           Action|Adventure|Biography|Drama|Western       5  
4  Action|Adventure|Biography|Drama|Romance|Thriller       4  
5  Action|Adventure|Biography|Drama|Romance|Thriller       5  
6          Action|Adventure|Biography|Drama|Thriller       9  
7               Action|Adventure|Biography|Drama|War       9  
8           Action|Adventure|Biography|Drama|Western      10  
9           Action|Adventure|Biography|Drama|Western       9

## Interpolate

In [131]:
data = 'Downloads/Movieratingdata4.csv'
df = pd.read_csv('Downloads/Movieratingdata4.csv')
df

DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR  RATING
0  25/01/2021      1.0   4642044           2015.0    10.0
1   25-2-2021      NaN   4642044              NaN     NaN
2   25-3-2021      3.0   1245897           2014.0     8.0
3   25-4-2021      NaN   1390411           2015.0     6.0
4   25-5-2021      NaN   6306064              NaN     NaN
5   25-6-2021      NaN   6306064           2020.0     4.0
6   25-7-2021      7.0   2719848           2015.0     4.0
7   25-8-2021      8.0    462504           2006.0     9.0
8   25-9-2021      9.0     25468           2015.0     NaN
9  25-10-2021     10.0   2564789           2015.0     9.0

In [132]:
df.interpolate()

DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR  RATING
0  25/01/2021      1.0   4642044           2015.0    10.0
1   25-2-2021      2.0   4642044           2014.5     9.0
2   25-3-2021      3.0   1245897           2014.0     8.0
3   25-4-2021      4.0   1390411           2015.0     6.0
4   25-5-2021      5.0   6306064           2017.5     5.0
5   25-6-2021      6.0   6306064           2020.0     4.0
6   25-7-2021      7.0   2719848           2015.0     4.0
7   25-8-2021      8.0    462504           2006.0     9.0
8   25-9-2021      9.0     25468           2015.0     9.0
9  25-10-2021     10.0   2564789           2015.0     9.0

In [133]:
pd.read_csv('Downloads/Movieratingdata4.csv',parse_dates = ['DATE'],index_col = 'DATE')

USER_ID  MOVIE_ID  PRODUCTION_YEAR  RATING
DATE                                                  
2021-01-25      1.0   4642044           2015.0    10.0
2021-02-25      NaN   4642044              NaN     NaN
2021-03-25      3.0   1245897           2014.0     8.0
2021-04-25      NaN   1390411           2015.0     6.0
2021-05-25      NaN   6306064              NaN     NaN
2021-06-25      NaN   6306064           2020.0     4.0
2021-07-25      7.0   2719848           2015.0     4.0
2021-08-25      8.0    462504           2006.0     9.0
2021-09-25      9.0     25468           2015.0     NaN
2021-10-25     10.0   2564789           2015.0     9.0

In [134]:
df.interpolate(method = 'index')

DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR  RATING
0  25/01/2021      1.0   4642044           2015.0    10.0
1   25-2-2021      2.0   4642044           2014.5     9.0
2   25-3-2021      3.0   1245897           2014.0     8.0
3   25-4-2021      4.0   1390411           2015.0     6.0
4   25-5-2021      5.0   6306064           2017.5     5.0
5   25-6-2021      6.0   6306064           2020.0     4.0
6   25-7-2021      7.0   2719848           2015.0     4.0
7   25-8-2021      8.0    462504           2006.0     9.0
8   25-9-2021      9.0     25468           2015.0     9.0
9  25-10-2021     10.0   2564789           2015.0     9.0

In [135]:
df.interpolate(method = 'nearest')

DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR  RATING
0  25/01/2021      1.0   4642044           2015.0    10.0
1   25-2-2021      1.0   4642044           2015.0    10.0
2   25-3-2021      3.0   1245897           2014.0     8.0
3   25-4-2021      3.0   1390411           2015.0     6.0
4   25-5-2021      3.0   6306064           2015.0     6.0
5   25-6-2021      7.0   6306064           2020.0     4.0
6   25-7-2021      7.0   2719848           2015.0     4.0
7   25-8-2021      8.0    462504           2006.0     9.0
8   25-9-2021      9.0     25468           2015.0     9.0
9  25-10-2021     10.0   2564789           2015.0     9.0

## Loc and ILoc method

In [136]:
data = 'Downloads/MovieratingdataLOC-ILOC.csv'
df = pd.read_csv('Downloads/MovieratingdataLOC-ILOC.csv')
df

DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2015      10
1   25-2-2021        2    FEB   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2015       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2015       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [137]:
df.loc[[1,2]]

DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
1  25-2-2021        2    FEB   4642044             2020       6
2  25-3-2021        3    MAR   1245897             2014       8

In [138]:
df.loc[1:4]

DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
1  25-2-2021        2    FEB   4642044             2020       6
2  25-3-2021        3    MAR   1245897             2014       8
3  25-4-2021        4  APRIL   1390411             2015       6
4  25-5-2021        5    MAY   6306064             2022       4

In [139]:
df

DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
0   25-1-2021        1    JAN   4642044             2015      10
1   25-2-2021        2    FEB   4642044             2020       6
2   25-3-2021        3    MAR   1245897             2014       8
3   25-4-2021        4  APRIL   1390411             2015       6
4   25-5-2021        5    MAY   6306064             2022       4
5   25-6-2021        6    JUN   6306064             2020       4
6   25-7-2021        7   JULY   2719848             2015       4
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [140]:
df.loc[1:4,['MONTHS','MOVIE_ID']]

MONTHS  MOVIE_ID
1    FEB   4642044
2    MAR   1245897
3  APRIL   1390411
4    MAY   6306064

In [141]:
df.loc[df['USER_ID']>7]

DATE  USER_ID MONTHS  MOVIE_ID  PRODUCTION_YEAR  RATING
7   25-8-2021        8    AUG    462504             2006       9
8   25-9-2021        9   SEPT     25468             2015       6
9  25-10-2021       10    OCT   2564789             2015       9

In [142]:
df.loc[df['PRODUCTION_YEAR']>2015,['RATING','MONTHS']]

RATING MONTHS
1       6    FEB
4       4    MAY
5       4    JUN

## Group By

In [143]:
data = 'Downloads/Movierating_groupby.csv'
df = pd.read_csv('Downloads/Movierating_groupby.csv')
df

USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
0        1        a        Holiday             2015       8
1        2        b        Holiday             2016       6
2        3        b         Spyder             2020       8
3        4        b          Krish             2020       5
4        5        c  Koyi mil gaya             2019       4
5        6        d  Koyi mil gaya             2020       5
6        7        d         Spyder             2015       9
7        8        e   Man in Black             2006       9
8        9        f         Spyder             2015      10
9       10        g   Man in Black             2015       9

In [144]:
a1 = df.groupby(by = 'MOVIE_ID')

In [145]:
df.groupby(by='MOVIE_ID').groups

{'a': [0], 'b': [1, 2, 3], 'c': [4], 'd': [5, 6], 'e': [7], 'f': [8], 'g': [9]}

In [146]:
for i in a:
    print(i)

1
2
3
4
5


In [147]:
df.groupby(['MOVIE_ID','PRODUCTION_YEAR']).groups

{('a', 2015): [0], ('b', 2016): [1], ('b', 2020): [2, 3], ('c', 2019): [4], ('d', 2015): [6], ('d', 2020): [5], ('e', 2006): [7], ('f', 2015): [8], ('g', 2015): [9]}

In [148]:
a = df.groupby(by='MOVIE_ID').get_group('b')
a

USER_ID MOVIE_ID MOVIE_TITLE  PRODUCTION_YEAR  RATING
1        2        b     Holiday             2016       6
2        3        b      Spyder             2020       8
3        4        b       Krish             2020       5

In [149]:
len(a)

3

In [150]:
b = df.groupby(by='MOVIE_ID').get_group('c')
b

USER_ID MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  RATING
4        5        c  Koyi mil gaya             2019       4

In [151]:
len(b)

1

In [152]:
a1.sum()

USER_ID  PRODUCTION_YEAR  RATING
MOVIE_ID                                  
a               1             2015       8
b               9             6056      19
c               5             2019       4
d              13             4035      14
e               8             2006       9
f               9             2015      10
g              10             2015       9

In [153]:
a1.agg(['min','max','mean','sum'])

USER_ID               PRODUCTION_YEAR                           \
             min max  mean sum             min   max         mean   sum   
MOVIE_ID                                                                  
a              1   1   1.0   1            2015  2015  2015.000000  2015   
b              2   4   3.0   9            2016  2020  2018.666667  6056   
c              5   5   5.0   5            2019  2019  2019.000000  2019   
d              6   7   6.5  13            2015  2020  2017.500000  4035   
e              8   8   8.0   8            2006  2006  2006.000000  2006   
f              9   9   9.0   9            2015  2015  2015.000000  2015   
g             10  10  10.0  10            2015  2015  2015.000000  2015   

         RATING                     
            min max       mean sum  
MOVIE_ID                            
a             8   8   8.000000   8  
b             5   8   6.333333  19  
c             4   4   4.000000   4  
d             5   9   7.000000  14  
e             9   9   9.000000   9  
f            10  10  10.000000  10  
g             9   9   9.000000   9

## Merge

In [154]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'CLASS':[11,12,13,14,15]})
df1

ID  CLASS
0   1     11
1   2     12
2   3     13
3   4     14
4   5     15

In [155]:
df2 = pd.DataFrame({'ID':[1,2,3,4,5],'name':['a','b','c','d','e']})
df2

ID name
0   1    a
1   2    b
2   3    c
3   4    d
4   5    e

In [156]:
pd.merge(df1,df2,on = 'ID')

ID  CLASS name
0   1     11    a
1   2     12    b
2   3     13    c
3   4     14    d
4   5     15    e

In [157]:
df1 = pd.DataFrame({'ID':[6,7,8,9,10],'CLASS':[11,12,13,14,15]})
df1

ID  CLASS
0   6     11
1   7     12
2   8     13
3   9     14
4  10     15

In [158]:
df2 = pd.DataFrame({'ID':[1,2,3,4,5],'name':['a','b','c','d','e']})
df2

ID name
0   1    a
1   2    b
2   3    c
3   4    d
4   5    e

In [159]:
pd.merge(df1,df2,on = 'ID',suffixes = ('_A','_B'),how = 'outer')

ID  CLASS name
0   6   11.0  NaN
1   7   12.0  NaN
2   8   13.0  NaN
3   9   14.0  NaN
4  10   15.0  NaN
5   1    NaN    a
6   2    NaN    b
7   3    NaN    c
8   4    NaN    d
9   5    NaN    e

In [160]:
pd.merge(df1,df2,on = 'ID',suffixes = ('_A','_B'),how = 'inner')

Empty DataFrame
Columns: [ID, CLASS, name]
Index: []

In [161]:
pd.merge(df1,df2,on = 'ID',suffixes = ('_A','_B'),how = 'left')

ID  CLASS name
0   6     11  NaN
1   7     12  NaN
2   8     13  NaN
3   9     14  NaN
4  10     15  NaN

In [162]:
pd.merge(df1,df2,on = 'ID',suffixes = ('_A','_B'),how = 'right')

ID  CLASS name
0   1    NaN    a
1   2    NaN    b
2   3    NaN    c
3   4    NaN    d
4   5    NaN    e

In [163]:
df2 = pd.DataFrame({'id':[1,2,3,4,5],'name':['a','b','c','d','e']})
df2   

id name
0   1    a
1   2    b
2   3    c
3   4    d
4   5    e

In [164]:
pd.merge(df1,df2,left_index = True,right_index = True)

ID  CLASS  id name
0   6     11   1    a
1   7     12   2    b
2   8     13   3    c
3   9     14   4    d
4  10     15   5    e

## Concat

In [165]:
sr1 = pd.Series([0,1,2,3,4])

In [166]:
sr2 = pd.Series([5,6,7,8,9])

In [167]:
sr3 = pd.Series([10,11,12,13,14])

In [168]:
pd.concat([sr1,sr2,sr3],axis = 1)

0  1   2
0  0  5  10
1  1  6  11
2  2  7  12
3  3  8  13
4  4  9  14

In [169]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'CLASS':[11,22,33,44,55]})

In [170]:
df2 = pd.DataFrame({'ID':[10,20,30,40,50],'CLASS':['A','B','C','D','E']})

In [171]:
pd.concat([df1,df2],axis = 1)

ID CLASS  ID CLASS
0   1    11  10     A
1   2    22  20     B
2   3    33  30     C
3   4    44  40     D
4   5    55  50     E

In [172]:
pd.concat([df1,df2],ignore_index = True)

ID CLASS
0   1    11
1   2    22
2   3    33
3   4    44
4   5    55
5  10     A
6  20     B
7  30     C
8  40     D
9  50     E

In [173]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'CLASS':[11,22,33,44,55]})

In [174]:
df2 = pd.DataFrame({'ID':[1,2,3],'CLASS':[11,22,33]})

In [175]:
pd.concat([df1,df2])

ID  CLASS
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55
0   1     11
1   2     22
2   3     33

In [176]:
pd.concat([df1,df2],axis = 1)

ID  CLASS   ID  CLASS
0   1     11  1.0   11.0
1   2     22  2.0   22.0
2   3     33  3.0   33.0
3   4     44  NaN    NaN
4   5     55  NaN    NaN

In [177]:
pd.concat([df1,df2],join = 'inner')

ID  CLASS
0   1     11
1   2     22
2   3     33
3   4     44
4   5     55
0   1     11
1   2     22
2   3     33

In [178]:
pd.concat([df1,df2],join = 'inner',axis = 1)

ID  CLASS  ID  CLASS
0   1     11   1     11
1   2     22   2     22
2   3     33   3     33

In [179]:
pd.concat([df1,df2],keys=['df1','df2'],axis = 0)

ID  CLASS
df1 0   1     11
    1   2     22
    2   3     33
    3   4     44
    4   5     55
df2 0   1     11
    1   2     22
    2   3     33

In [180]:
pd.concat([df1,df2],keys=['df1','df2'],axis = 1)

df1        df2      
   ID CLASS   ID CLASS
0   1    11  1.0  11.0
1   2    22  2.0  22.0
2   3    33  3.0  33.0
3   4    44  NaN   NaN
4   5    55  NaN   NaN

In [181]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'name':[11,22,33,44,55]})

In [182]:
df2 = pd.DataFrame({'ID2':[10,20,30,40,50],'class':[11,22,33,44,55]})

In [183]:
pd.concat([df1,df2])

ID  name   ID2  class
0  1.0  11.0   NaN    NaN
1  2.0  22.0   NaN    NaN
2  3.0  33.0   NaN    NaN
3  4.0  44.0   NaN    NaN
4  5.0  55.0   NaN    NaN
0  NaN   NaN  10.0   11.0
1  NaN   NaN  20.0   22.0
2  NaN   NaN  30.0   33.0
3  NaN   NaN  40.0   44.0
4  NaN   NaN  50.0   55.0

In [184]:
pd.concat([df1,df2],axis = 0)

ID  name   ID2  class
0  1.0  11.0   NaN    NaN
1  2.0  22.0   NaN    NaN
2  3.0  33.0   NaN    NaN
3  4.0  44.0   NaN    NaN
4  5.0  55.0   NaN    NaN
0  NaN   NaN  10.0   11.0
1  NaN   NaN  20.0   22.0
2  NaN   NaN  30.0   33.0
3  NaN   NaN  40.0   44.0
4  NaN   NaN  50.0   55.0

In [185]:
df1 = pd.DataFrame({'ID1':[1,2,3,4,5],'CLASS':[10,20,30,40,50]})

In [186]:
df2 = pd.DataFrame({'ID2':[1,2,3,4,5],'NAME':[10,20,30,40,50]})

In [187]:
df1.join(df2)

ID1  CLASS  ID2  NAME
0    1     10    1    10
1    2     20    2    20
2    3     30    3    30
3    4     40    4    40
4    5     50    5    50

In [188]:
df1 = pd.DataFrame({'ID1':[1,2,3,4,5],'CLASS':[10,20,30,40,50]},index = ['a','b','c','d','e'])

In [189]:
df2 = pd.DataFrame({'ID2':[1,2,3,4,5],'NAME':[10,20,30,40,50]})

In [190]:
df1.join(df2)

ID1  CLASS  ID2  NAME
a    1     10  NaN   NaN
b    2     20  NaN   NaN
c    3     30  NaN   NaN
d    4     40  NaN   NaN
e    5     50  NaN   NaN

In [191]:
df1 = pd.DataFrame({'ID1':[1,2,3,4,5],'CLASS':[10,20,30,40,50]})

In [192]:
df2 = pd.DataFrame({'ID2':[1,2,3],'NAME':[10,20,30]})

In [193]:
df1.join(df2)

ID1  CLASS  ID2  NAME
0    1     10  1.0  10.0
1    2     20  2.0  20.0
2    3     30  3.0  30.0
3    4     40  NaN   NaN
4    5     50  NaN   NaN

In [194]:
df1 = pd.DataFrame({'ID':[1,2,3,4,5],'CLASS':[10,20,30,40,50]})

In [195]:
df2 = pd.DataFrame({'ID':[1,2,3,4,5],'NAME':[10,20,30,40,50]})

In [196]:
df1.join(df2,lsuffix='_1')

ID_1  CLASS  ID  NAME
0     1     10   1    10
1     2     20   2    20
2     3     30   3    30
3     4     40   4    40
4     5     50   5    50

In [197]:
df1.join(df2,rsuffix='_1',how='left')

ID  CLASS  ID_1  NAME
0   1     10     1    10
1   2     20     2    20
2   3     30     3    30
3   4     40     4    40
4   5     50     5    50

In [198]:
df1 = pd.DataFrame({'ID1':[1,2,3,4,5],'CLASS':[10,20,30,40,50]})

In [199]:
df2 = pd.DataFrame({'ID2':[1,2,3,4,5],'NAME':[10,20,30,40,50]})

In [200]:
df1.append(df2)

ID1  CLASS  ID2  NAME
0  1.0   10.0  NaN   NaN
1  2.0   20.0  NaN   NaN
2  3.0   30.0  NaN   NaN
3  4.0   40.0  NaN   NaN
4  5.0   50.0  NaN   NaN
0  NaN    NaN  1.0  10.0
1  NaN    NaN  2.0  20.0
2  NaN    NaN  3.0  30.0
3  NaN    NaN  4.0  40.0
4  NaN    NaN  5.0  50.0

## Data Preprocessing

In [201]:
import pandas as pd
import numpy as np

In [202]:
df = pd.DataFrame({'A':[8,3,None,4,7],'B':[None,2,4,3,5],'C':[4,None,8,5,None],'D':[None,4,2,None,1]})

In [203]:
df

A    B    C    D
0  8.0  NaN  4.0  NaN
1  3.0  2.0  NaN  4.0
2  NaN  4.0  8.0  2.0
3  4.0  3.0  5.0  NaN
4  7.0  5.0  NaN  1.0

In [204]:
from sklearn.impute import SimpleImputer

In [205]:
imputer = SimpleImputer()

In [206]:
df[['A','C','D']] = imputer.fit_transform(df[['A','C','D']])

In [207]:
df

A    B         C         D
0  8.0  NaN  4.000000  2.333333
1  3.0  2.0  5.666667  4.000000
2  5.5  4.0  8.000000  2.000000
3  4.0  3.0  5.000000  2.333333
4  7.0  5.0  5.666667  1.000000

In [208]:
imputer = SimpleImputer(missing_values = None,strategy='most_frequent')

In [209]:
df1 = pd.DataFrame({'A':['apple',None,'kiwi','orange','kiwi',None,'cherry','kiwi'],
              'B':['lady finger','spinach',None,'lady finger','cabbage',None,'lady finger','spinach'],
              'C':['burger','pizza','burger','wrap',None,'fries','burger','burger']})


In [210]:
df1[['A','B','C']] = imputer.fit_transform(df[['A','B','C']])

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
df1

## Data Encoding

In [211]:
import pandas as pd
import numpy as np

In [212]:
df1 = pd.read_csv("Downloads/encoding.csv")
df1

Total_bill  Gender  Day    Time  Size
0         250  female  sun  Dinner     5
1         260  female  sat  Dinner     6
2         350  female  sun  Dinner     4
3         250    male  sat   Lunch     3
4         892    male  sat   Lunch     0
5         745  female  sun  Dinner     2
6         455    male  fri  Dinner     4
7         564    male  fri  Dinner     0
8         452  female  sat   Lunch     2
9         349    male  sat   Lunch     1

In [213]:
pd.get_dummies(df1)

Total_bill  Size  Gender_female  Gender_male  Day_fri  Day_sat  Day_sun  \
0         250     5              1            0        0        0        1   
1         260     6              1            0        0        1        0   
2         350     4              1            0        0        0        1   
3         250     3              0            1        0        1        0   
4         892     0              0            1        0        1        0   
5         745     2              1            0        0        0        1   
6         455     4              0            1        1        0        0   
7         564     0              0            1        1        0        0   
8         452     2              1            0        0        1        0   
9         349     1              0            1        0        1        0   

   Time_Dinner  Time_Lunch  
0            1           0  
1            1           0  
2            1           0  
3            0           1  
4            0           1  
5            1           0  
6            1           0  
7            1           0  
8            0           1  
9            0           1

In [214]:
pd.get_dummies(df1,drop_first = True)

Total_bill  Size  Gender_male  Day_sat  Day_sun  Time_Lunch
0         250     5            0        0        1           0
1         260     6            0        1        0           0
2         350     4            0        0        1           0
3         250     3            1        1        0           1
4         892     0            1        1        0           1
5         745     2            0        0        1           0
6         455     4            1        0        0           0
7         564     0            1        0        0           0
8         452     2            0        1        0           1
9         349     1            1        1        0           1

## ONe HOT encoder

In [215]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
encoder = OneHotEncoder(sparse=False)

In [216]:
a = encoder.fit_transform(df1[['Gender','Day','Time']])

In [217]:
a

array([[1., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 1.]])

In [218]:
pd.DataFrame(a,columns = ['female','male','fri','sat','sun','lunch','dinner'])

female  male  fri  sat  sun  lunch  dinner
0     1.0   0.0  0.0  0.0  1.0    1.0     0.0
1     1.0   0.0  0.0  1.0  0.0    1.0     0.0
2     1.0   0.0  0.0  0.0  1.0    1.0     0.0
3     0.0   1.0  0.0  1.0  0.0    0.0     1.0
4     0.0   1.0  0.0  1.0  0.0    0.0     1.0
5     1.0   0.0  0.0  0.0  1.0    1.0     0.0
6     0.0   1.0  1.0  0.0  0.0    1.0     0.0
7     0.0   1.0  1.0  0.0  0.0    1.0     0.0
8     1.0   0.0  0.0  1.0  0.0    0.0     1.0
9     0.0   1.0  0.0  1.0  0.0    0.0     1.0

## LAble Encoder

In [219]:
le = LabelEncoder()

In [220]:
le.fit_transform(df1[['Day']])

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([2, 1, 2, 1, 1, 2, 0, 0, 1, 1])

## Feature Scaling

In [221]:
df = pd.read_csv("Downloads/encoding.csv")
df

Total_bill  Gender  Day    Time  Size
0         250  female  sun  Dinner     5
1         260  female  sat  Dinner     6
2         350  female  sun  Dinner     4
3         250    male  sat   Lunch     3
4         892    male  sat   Lunch     0
5         745  female  sun  Dinner     2
6         455    male  fri  Dinner     4
7         564    male  fri  Dinner     0
8         452  female  sat   Lunch     2
9         349    male  sat   Lunch     1

In [222]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [223]:
a = df[['Total_bill','Size']]

In [224]:
ss = StandardScaler()

In [225]:
ss.fit_transform(a)

array([[-0.99533165,  1.1783257 ],
       [-0.94717821,  1.69064121],
       [-0.51379723,  0.66601018],
       [-0.99533165,  0.15369466],
       [ 2.09611935, -1.3832519 ],
       [ 1.38826374, -0.35862086],
       [-0.00818609,  0.66601018],
       [ 0.51668644, -1.3832519 ],
       [-0.02263212, -0.35862086],
       [-0.51861257, -0.87093638]])

In [226]:
mms = MinMaxScaler()

In [227]:
mms.fit_transform(a)

array([[0.        , 0.83333333],
       [0.01557632, 1.        ],
       [0.15576324, 0.66666667],
       [0.        , 0.5       ],
       [1.        , 0.        ],
       [0.77102804, 0.33333333],
       [0.31931464, 0.66666667],
       [0.48909657, 0.        ],
       [0.31464174, 0.33333333],
       [0.15420561, 0.16666667]])

In [ ]:
!jt -t gruvboxd -T -fs 13